# Generated by Django 5.0.4 on 2024-04-22 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', message='Invite code must consist of letters and numbers')], verbose_name='Инвайт-код'),
        ),
    ]
